
---
title: "Barplot Analysis of Juvenile HFD Study"
author: "Dave Bridges"
date: "August 13, 2015"
output:
  html_document:
    keep_md: true
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(digits=3, scipen=8)
```

Used analysed DESeq results.  This script was most recently run on `r date()`.

```{r file-input}
filename <- "Normalized Counts.csv"
deseq.filename.wat <- "DESeq Results for Effects of Diet on WAT.csv"
mapping.filename <- "../sample-mapping.csv"
annotation.filename <- "ENSEMBL Annotation.csv"
#read in the file
normalized.data <- read.csv(filename, row.names='X')
deseq.data.wat <- read.csv(deseq.filename.wat)
mapping <- read.csv(mapping.filename)
mapping$samplename <- paste("sample", mapping$sample.., sep="")
mapping$Diet <- relevel(mapping$Diet, ref="Control Diet")
annotation <- read.csv(annotation.filename, row.names="X")

colnames(normalized.data) <- gsub("X", "", colnames(normalized.data))
colnames(normalized.data) <- gsub("\\.", "-", colnames(normalized.data))
```

This script uses the DESeq files `r deseq.filename.wat` and the mapping file `r mapping.filename`.  It uses the annotation data found in `r annotation.filename`.  The normalized counts are found in `r filename`.

# Adipocytes

```{r adipose-barplots}
#get columns for adipose data
adipose.normalized.data <- normalized.data[,levels(droplevels(subset(mapping, Tissue=="eWAT")$SampleID))]
#remove decimal from gene name
adipose.normalized.data$ensembl_gene_id <- as.character(lapply(strsplit(rownames(adipose.normalized.data), "\\."), "[[", 1))

rpkm.data <- merge(adipose.normalized.data, annotation, by='ensembl_gene_id') 
rpkm.data.unique <- rpkm.data[!duplicated(rpkm.data$external_gene_name),]

rownames(rpkm.data.unique) <- rpkm.data.unique$external_gene_name
rpkm.data.unique <- rpkm.data.unique[,-1]

#set genes for single barplots
genes.of.interest <- c("Retn","Pparg","Lep","Hsd11b1","Pnpla2","Tbc1d9b","Clk4","Slc1a3","Ap2s1","Rer1","Ywhae")

#get a table of just the genes of interest
genes.of.interest.data <- rpkm.data.unique[genes.of.interest,]
#put the data in long format
library(tidyr)
library(dplyr)
genes.of.interest.long <- 
  genes.of.interest.data %>%
  select(-gene_biotype) %>%
  gather(SampleID, expression, -external_gene_name)
goi.long <- merge(mapping, genes.of.interest.long, by="SampleID")

goi.long.cal <- 
  goi.long %>%
  group_by(external_gene_name, Feeding,Diet) %>%
  summarize(Average = mean(expression),
            SE = sd(expression)/sqrt(length(expression)))
```

Drew bargraphs for *`r paste(genes.of.interest, collapse=", ")`*.

```{r barplots}
library(ggplot2)
for (gene in genes.of.interest) {
  #pdf(sprintf('../figures/%s-barplot.pdf', gene))
  gene.data <- goi.long.cal[goi.long.cal$external_gene_name==gene,]
  #pdf(paste('../figures/',gene,'-barplot.pdf',sep=""))
  p <- ggplot(gene.data, aes(x=Diet,y=Average,fill=Feeding))
  dodge <- position_dodge(width=0.9)
  p <- p + geom_bar(position=dodge, stat="identity") + geom_errorbar(aes(ymin=Average-SE, ymax=Average+SE), position=dodge, width=0.1) 
  
  p + xlab("") + ylab("mRNA Expression (RPKM)")+ theme_bw() + ggtitle(gene) + theme(panel.grid.minor = element_blank()) + theme(panel.grid.major = element_blank()) + theme(panel.border=element_blank()) + scale_x_discrete(labels=gene.data$Diet) + theme(axis.line = element_line(color = 'black'))+scale_colour_grey(start = 0.5, end = .9)
  ggsave(filename=paste('figures/barplots/Adipose-',gene,'-barplot.pdf',sep=""))
}

```

Session Information
---------------------

```{r session-information}
sessionInfo()
```
