---
title: "compare_kallisto_htseq"
author: "Quynh Tran"
date: "March 4, 2016"
output: html_document
---
This script compares the padjusted values obtained from htseq and kallisto counts to see if the conclusions are consistent between the two analyses.

Used analysed DESeq results.  This script was most recently run on `r date()`.

Comparison 
-------

```{r compare_adjP, echo=FALSE}
#gene.in.htseq <- unique(deseq.data.htseq$external_gene_name)
#number of agreement

compare <- function(in_file_kal, in_file_htseq, p_type, out_file){
  unique.kal.data <- read.csv(in_file_kal)
  deseq.data.htseq <- read.csv(in_file_htseq)
  gene.name <- unique(unique.kal.data$external_gene_name)
  agree = 0
  disagree = 0
  disagreeNA = 0
  
  for (gene in gene.name){
    p.htseq <- deseq.data.htseq[which(deseq.data.htseq$external_gene_name==gene), p_type]
    p.kallisto <- unique.kal.data[which(unique.kal.data$external_gene_name==gene), p_type]
    if (!is.na(p.htseq) & (!is.na(p.kallisto)[1])) { #none of the p-values are NA
      if ((p.htseq > 0.05 & p.kallisto > 0.05) | (p.htseq < 0.05 & p.kallisto < 0.05)){
        agree = agree + 1
      }
      else{
        disagree = disagree + 1
      }
    } else{
        if (is.na(p.htseq) & (is.na(p.kallisto)[1])){ #both p-values are NA
          agree=agree+1
        }
        else{ # either value is NA
          disagreeNA=disagreeNA+1
        }
    }
  }
  total = agree+disagree+disagreeNA
  stat_data <- data.frame(agree, disagree, disagreeNA)
  stat_data$agreePercent <- (stat_data$agree/total)*100
  stat_data$disagreePercent <- (stat_data$disagree/total)*100
  stat_data$disagreeNAPercent <- (stat_data$disagreeNA/total)*100
  write.csv(stat_data, file=out_file)
}

feeding_p = "padj_Feeding"
diet_p = "padj_Diet"
interaction_p = "padj"
#agreement_stat_filename = "Agreement_stat_Combined_Model_Interaction_Quad.csv"
unique_filename_kal = "Unique_Transcript_DESeq_Results_Combined_Effects_Quadriceps_Kallisto.csv"
deseq_filename_htseq <- "DESeq Results for Effects of Combined Model on Quad.csv"

compare(unique_filename_kal, deseq_filename_htseq, feeding_p, paste("Agreement_results/Agreement_stat_Combined_Model", feeding_p, "Quad.csv", sep="_"))
compare(unique_filename_kal, deseq_filename_htseq, diet_p, paste("Agreement_results/Agreement_stat_Combined_Model", diet_p, "Quad.csv",sep="_"))
compare(unique_filename_kal, deseq_filename_htseq, interaction_p, "Agreement_results/Agreement_stat_Combined_Model_Interaction_Quad.csv")

unique_filename_kal1 = "Unique_Transcript_DESeq_Results_Combined_Effects_WAT_Kallisto.csv"
deseq_filename_htseq1 <- "DESeq Results for Effects of Combined Model on WAT.csv"

compare(unique_filename_kal1, deseq_filename_htseq1, feeding_p, paste("Agreement_results/Agreement_stat_Combined_Model", feeding_p, "WAT.csv", sep="_"))
compare(unique_filename_kal1, deseq_filename_htseq1, diet_p, paste("Agreement_results/Agreement_stat_Combined_Model", diet_p, "WAT.csv", sep="_"))
compare(unique_filename_kal1, deseq_filename_htseq1, interaction_p, "Agreement_results/Agreement_stat_Combined_Model_Interaction_WAT.csv")

```

  <!--The number of agreement in conclusions based on padj between htseq and kallisto based counts is . The number of disagreement where one of the p-values is NA is . The number of disagreement when one of the p-values <0.05 but the other is >0.05 is .-->
  
  Session Information
---------------------

```{r session-information}
sessionInfo()
```