---
title: "Making Input Files for GSEA Analyses"
author: "Dave Bridges, Quynh Tran"
date: "August 9, 2015"
output:
  html_document:
    keep_md: true
---

Making the input files
----------------------

```{r Read-data, echo=FALSE}

deseq_file_quads <- "results/DESeq_Combined_Model_Quadricep_Unique_Kalllisto.csv"
deseq.results.quads <- read.csv(deseq_file_quads)

#order by pvalue and get rid of those with NA foldchange
results.noNA <- deseq.results.quads[which(deseq.results.quads$log2FoldChange_Feeding != 'NA'),]
results.noNA.ordered <- results.noNA[order(results.noNA$log2FoldChange_Feeding),c('external_gene_name','log2FoldChange_Feeding')]
#get rid of duplicate genes
#results.noDup <- results.noNA[!duplicated(results.noNA$external_gene_name),]
result_data_file_quads <- "results/GSEA_prerank_Quadriceps_feeding_kallisto.rnk"
write.table(results.noNA.ordered, file=result_data_file_quads, sep="\t", quote=FALSE, row.names=FALSE)

deseq_file_wat <- "results/DESeq_Combined_Model_WAT_Unique_Kalllisto.csv"
deseq.results.wat <- read.csv(deseq_file_wat)

#order by pvalue and get rid of those with NA foldchange
results.noNA <- deseq.results.wat[which(deseq.results.wat$log2FoldChange != 'NA'),]
results.noNA <- results.noNA[order(results.noNA$log2FoldChange),c('external_gene_name','log2FoldChange')]
#get rid of duplicate genes
results.noDup <- results.noNA[!duplicated(results.noNA$external_gene_name),]
result_data_file_wat <- "results/GSEA_prerank_WAT_interaction_kallisto.rnk"
write.table(results.noDup, file=result_data_file_wat, sep="\t", quote=FALSE, row.names=FALSE)
```

This script takes the input files `r deseq_file_quads` and `r deseq_file_wat`.  This script was most recently run on `r date()`.  It writes out to the data files `r result_data_file_quads` and `r result_data_file_wat`.

## GSEA Analysis

Used GSEA version 2.2 downloaded from http://www.broadinstitute.org/gsea/index.jsp.  Some notes on the actual analyses

* Used preranked list, ordered by log2fold change
* Ran 1000 permutations
* Compared to MSigDB database version 5.0
* Looked at gene sets with between 10 and 5000 members
* Used **weighted** enrichment statistic

The analysis was done against the following gene sets:

* Gene Ontology - Cellular Component 
* Gene Ontology - Biological Process
* Gene Ontology - Molecular Function
* KEGG
* Reactome
* Biocarta
* miRNA
* TFT, TRANSFAC 7.4



Session Information
---------------------

```{r session-information, echo=FALSE}
sessionInfo()
```