---
title: "remove_redundant_transcripts"
author: "Quynh Tran"
date: "March 3, 2016"
output: html_document
---
This script will go through the deseq results obtained from kallisto counts and keep the transcript with the highest base mean expression counts for each gene. 

Used analysed DESeq results.  This script was most recently run on `r date()`.

```{r file-input, echo=FALSE, message=FALSE}
deseq.filename.kal <- "DESeq Results for Effects of Combined Model on Quadriceps - Kallisto.csv"
deseq.filename.htseq <- "DESeq Results for Effects of Combined Model on Quad.csv"

unique_file_name = "Unique_Transcript_DESeq_Results_Combined_Effects_Quadriceps_Kallisto.csv"

deseq.filename.kal1 <- "DESeq Results for Effects of Combined Model on WAT - Kalllisto.csv"
deseq.filename.htseq1 <- "DESeq Results for Effects of Combined Model on WAT.csv"

unique_file_name1 = "Unique_Transcript_DESeq_Results_Combined_Effects_WAT_Kallisto.csv"
```

Remove redundant transcripts that do not have NA in their base mean counts
------------------

```{r remove_redundancy, echo=FALSE}
remove_redundancy <- function(kal_file, htseq_file, out_file){
  #read in the file
  deseq.data.kal <- read.csv(kal_file)
  deseq.data.htseq <- read.csv(htseq_file)

  unique.kal.data <- NULL
  #unique.kal.data <- colnames(deseq.data.kal)
  gene.name <- unique(deseq.data.kal$external_gene_name)
  
  for (g in gene.name){
    sub <- subset(deseq.data.kal, external_gene_name==g)
    #print(sub)
    max.mean <- round(max(sub$baseMean),0)
    if (max.mean != 0){
      subset.max <- sub[which(sub$baseMean==max(sub$baseMean)),]
      unique.kal.data <- rbind(unique.kal.data, subset.max)
    } else{
        if (nrow(sub)>1){
          unique.kal.data <-rbind(unique.kal.data, sub[1,])
        }else{
          unique.kal.data <-rbind(unique.kal.data, sub)
        }
    }
    #print(unique.kal.data)
  }
  write.csv(unique.kal.data, file=out_file)
}

remove_redundancy(deseq.filename.kal, deseq.filename.htseq, unique_file_name)
remove_redundancy(deseq.filename.kal1, deseq.filename.htseq1, unique_file_name1)
```
  The output file contains unique gene names for kallisto is `r unique_file_name`. This file contains unique gene names for those that do not have NA values for their base mean counts only.
  

  
Session Information
---------------------

```{r session-information}
sessionInfo()
```
