---
title: "HFD_make_evaluation_data"
author: "Quynh Tran"
date: "March 27, 2015"
output: html_document
---
```{r pulling data from the database, echo=FALSE}
# url.cohort9.group1 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=1000&offset=0&animal__cohort=15'
# url.cohort9.group2 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=1000&offset=1000&animal__cohort=15'
# 
# library(rjson)
# library(RCurl)
# json.cohort9.group1 <- fromJSON(getURL(url.cohort9.group1))
# json.cohort9.group2 <- fromJSON(getURL(url.cohort9.group2))
# 
# library(plyr)
# cohort9.data.1 <- rbind(ldply(lapply(json.cohort9.group1[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame))
# cohort9.data.2 <- rbind(ldply(lapply(json.cohort9.group2[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame))
# #cohort9.data$animal.MouseID <- as.factor(cohort9.data$animal.MouseID)
# 
# useful.columns <- intersect(colnames(cohort9.data.1), colnames(cohort9.data.2))
# cohort9.data <- rbind(cohort9.data.1[,useful.columns],
#               cohort9.data.2[,useful.columns])
 raw_output_file <- "../data/raw/Cohort 9 Raw Data.csv"
# write.csv(cohort9.data, raw_output_file)
 cohort9.data <- read.csv(raw_output_file, row.names="X")

date_after_fasting <- '2014-12-02'
date_before_fasting <- '2014-12-01'
date_10weeks_MRI <- '2015-02-24'
#only look at fed, fasted and 10w data
date_of_interest <- c('2014-12-01', '2014-12-02', '2015-02-24')

sub_cohort9.data <- cohort9.data[cohort9.data$experiment.date %in% date_of_interest,]

#sub_cohort9.data <- cohort9.data[cohort9.data$animal.MouseID!=2119, ]
sub_cohort9.data$animal.MouseID <- as.factor(sub_cohort9.data$animal.MouseID)
#Rename the fasting stage based on the date
sub_cohort9.data$Fasting_stat <- ifelse(sub_cohort9.data$experiment.date==date_before_fasting, "Pre_fasting",ifelse(sub_cohort9.data$experiment.date==date_after_fasting,"After_fasting","After_HFD"))

#import body composition data
library(reshape2)
cohort9_weight <-dcast(sub_cohort9.data, animal.MouseID+Fasting_stat~assay.assay, value.var='values')

cohort9_weight$Lean <- as.numeric(cohort9_weight$'Lean Mass')/1000
cohort9_weight$Fat <- as.numeric(cohort9_weight$'Total Fat Mass')/1000
cohort9_weight$Weight <- as.numeric(cohort9_weight$'Body Weight')/1000
#calculate percent body fat
cohort9_weight$Percent.Fat <- cohort9_weight$Fat/cohort9_weight$Weight*100
#make animal id a factor
cohort9_weight$Subject <- as.factor(cohort9_weight$animal.MouseID)
cohort9_weight$Fasting_stat <- as.factor(cohort9_weight$Fasting_stat)
#set Pre_fasting as the reference level
cohort9_weight$Fasting_stat <- relevel(as.factor(cohort9_weight$Fasting_stat), ref='Pre_fasting')

```
# Body Weight Analysis
```{r body-weight, echo=FALSE}
se <- function(x) sd(x)/sqrt(length(x))
library(ggplot2)
library(dplyr)
body_weight_summary <-
  cohort9_weight %>%
  group_by(Fasting_stat) %>%
  summarise(
    Weight = mean(Weight),
    Fat = mean(Fat),
    Lean = mean(Lean),
    Percent.Fat = mean(Percent.Fat))

body_weight_err <-
  cohort9_weight %>%
  group_by(Fasting_stat) %>%
  summarise(
    Weight = se(Weight),
    Fat = se(Fat),
    Lean = se(Lean),
    Percent.Fat = se(Percent.Fat))

body_weight_shapiro <-
  cohort9_weight %>%
  group_by(Fasting_stat) %>%
  summarise(
    Weight = shapiro.test(Weight)$p.value,
    Fat = shapiro.test(Fat)$p.value,
    Lean = shapiro.test(Lean)$p.value,
    Percent.Fat = shapiro.test(Percent.Fat)$p.value)

body_weight_delta <-
  cohort9_weight %>%
  group_by(animal.MouseID) %>%
  mutate(
    Delta_weight=c(0,diff(Weight)))

delta_weight<-body_weight_delta[body_weight_delta$Fasting_stat=="Pre_fasting",c(1,8,9,11)]

library(car)
body.weight.bartlett <- data.frame()
body.weight.bartlett['Weight','pval'] <- bartlett.test(Weight~Fasting_stat, data=cohort9_weight)$p.value
body.weight.bartlett['Fat','pval'] <- bartlett.test(Fat~Fasting_stat, data=cohort9_weight)$p.value
body.weight.bartlett['Lean','pval'] <- bartlett.test(Lean~Fasting_stat, data=cohort9_weight)$p.value
body.weight.bartlett['Percent.Fat','pval'] <- bartlett.test(Percent.Fat~Fasting_stat, data=cohort9_weight)$p.value

superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

par(mfrow=c(2,2))
ymax <- max(body_weight_summary$Weight + body_weight_err$Weight)
plot <- barplot(as.numeric(body_weight_summary$Weight),
                beside=T, las=1, main="Body Weight", ylim=c(0,ymax), col=c('blue','green','red'))
superpose.eb(plot,
             as.numeric(body_weight_summary$Weight),
             as.numeric(body_weight_err$Weight))

ymax <- max(body_weight_summary$Fat + body_weight_err$Fat)
plot <- barplot(as.numeric(body_weight_summary$Fat),
                beside=T, las=1, main="Total Fat Mass", ylim=c(0,ymax), col=c('blue','green','red'))

superpose.eb(plot,
             as.numeric(body_weight_summary$Fat),
             as.numeric(body_weight_err$Fat))

ymax <- max(body_weight_summary$Lean + body_weight_err$Lean)
plot <- barplot(as.numeric(body_weight_summary$Lean),
                beside=T, las=1, main="Lean Mass", ylim=c(0,ymax), col=c('blue','green','red'), names.arg=c("Prefasting","AfterFasting","AfterHFD"))
superpose.eb(plot,
             as.numeric(body_weight_summary$Lean),
             as.numeric(body_weight_err$Lean))

ymax <- max(body_weight_summary$Percent.Fat + body_weight_err$Percent.Fat)
plot <- barplot(as.numeric(body_weight_summary$Percent.Fat),
                beside=T, las=1, main="Percent Fat Mass", ylim=c(0,ymax), col=c('blue','green','red'),names.arg=c("Prefasting","AfterFasting","AfterHFD"))
superpose.eb(plot,
             as.numeric(body_weight_summary$Percent.Fat),
             as.numeric(body_weight_err$Percent.Fat))

ggplot(cohort9_weight, aes(x=Fasting_stat, y=Weight, group=Subject, colour=Subject)) + geom_point()+geom_line()+
  xlab("Fasting status")+
  ylab("Weight (g)")
```

#CLAMS data
```{r import-and-process-clams-data, echo=FALSE}

#import CLAMS data
filename <- '../data/raw/Oxymax-2014-11-26.csv'
cohort9_clams <- read.csv(filename)
#remove commented data
cohort9_clams <- cohort9_clams[cohort9_clams$Event.Log=="",]
#data$Subject <- as.factor(data$Subject)
#mark which ones are actually in this experiment
start_fasting_interval <- 229
stop_fasting_interval <- 261
interval_time <- 32
#calculated elapsed time in hours
cohort9_clams$Intervals.Elapsed <- cohort9_clams$Interval - min(cohort9_clams$Interval)
cohort9_clams$Time <- cohort9_clams$Intervals.Elapsed * interval_time/60
cohort9_clams$Subject <- as.factor(cohort9_clams$Subject)
#determine dark/light cycles
#calculate when the first dark cycle starts
first.dark.cycle <- min(cohort9_clams[cohort9_clams$Light.Dark=='Dark',]$Time)
dark.cycles <- data.frame(
  Day1 = c(Start=first.dark.cycle,End=first.dark.cycle+12),
  Day2 = c(Start=first.dark.cycle+24,End=first.dark.cycle+36),
  Day3 = c(Start=first.dark.cycle+48,End=first.dark.cycle+60),
  Day4 = c(Start=first.dark.cycle+72,End=first.dark.cycle+84),
  Day5 = c(Start=first.dark.cycle+96,End=first.dark.cycle+108),
  Day6 = c(Start=first.dark.cycle+120,End=first.dark.cycle+132),
  Day7 = c(Start=first.dark.cycle+144,End=first.dark.cycle+156)
)
write.csv(cohort9_clams, file="../data/processed/cohort9_Oxymax.csv")
```

# VO2 Data

```{r vo2-raw-data, echo=FALSE}
#merge the weight and clams data
annotated_clams_data <- merge(cohort9_weight, cohort9_clams, by='Subject')
annotated_clams_data$VO2 <- annotated_clams_data$Volume.O2*annotated_clams_data$Weight/1000

#filtered out bad numbers

#first filtered out any reading with a comment
annotated_clams_data <- subset(annotated_clams_data, Event.Log=='')
#which mice have a negative delta CO2
annotated_clams_data <- subset(annotated_clams_data, Volume.CO2>100)
annotated_clams_data <- subset(annotated_clams_data, Volume.O2>100)

write.csv(cohort9_clams, file="../data/processed/clams_testing_data.csv")

```

````{r correlation_matrix, echo=FALSE}
sub_cohort9_weight <- cohort9_weight[, c('Subject','Lean','Fat','Weight','Percent.Fat','Fasting_stat')]
cohort9_weight_wide <- reshape(sub_cohort9_weight, idvar="Subject", timevar="Fasting_stat", 
                               v.names=c("Lean","Fat","Weight","Percent.Fat"), direction="wide")
#calculate the weight loss percentage
cohort9_weight_wide$Percent.WL <- as.numeric((cohort9_weight_wide$Weight.Pre_fasting - cohort9_weight_wide$Weight.After_fasting)/cohort9_weight_wide$Weight.Pre_fasting*100)
#calculated weight gain relative to fed weight
cohort9_weight_wide$Percent.WG <- as.numeric((cohort9_weight_wide$Weight.After_HFD - cohort9_weight_wide$Weight.Pre_fasting)/cohort9_weight_wide$Weight.Pre_fasting*100)
#calculated lean loss during fast
cohort9_weight_wide$Percent.LL <- as.numeric((cohort9_weight_wide$Lean.Pre_fasting - cohort9_weight_wide$Lean.After_fasting)/cohort9_weight_wide$Lean.Pre_fasting*100)
#calculated lean weight gain during diet relative to fed weight
cohort9_weight_wide$Percent.LG <- as.numeric((cohort9_weight_wide$Lean.After_HFD - cohort9_weight_wide$Lean.Pre_fasting)/cohort9_weight_wide$Lean.Pre_fasting*100)
#calculated fat loss during fast
cohort9_weight_wide$Percent.FL <- as.numeric((cohort9_weight_wide$Fat.Pre_fasting - cohort9_weight_wide$Fat.After_fasting)/cohort9_weight_wide$Fat.Pre_fasting*100)
#calculated fat gain during the diet relative to fed weight
cohort9_weight_wide$Percent.FG <- as.numeric((cohort9_weight_wide$Fat.After_HFD - cohort9_weight_wide$Fat.Pre_fasting)/cohort9_weight_wide$Fat.Pre_fasting*100)

#save the body composition data
write.csv(cohort9_weight, file="../data/processed/body_compostition_testing_data.csv")

panel.cor <- function(x, y, digits=2, cex.cor)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  test <- cor.test(x,y)
  Signif <- ifelse(round(test$p.value,3)<0.001,"p<0.001",paste("p=",round(test$p.value,3)))  
  text(0.5, 0.25, paste("r=",txt))
  text(.5, .75, Signif)
}

panel.smooth<-function (x, y, col = "blue", bg = NA, pch = 18, 
                        cex = 0.8, col.smooth = "red", span = 2/3, iter = 3, ...) 
{
  points(x, y, pch = pch, col = col, bg = bg, cex = cex)
  ok <- is.finite(x) & is.finite(y)
  if (any(ok)) 
    lines(stats::lowess(x[ok], y[ok], f = span, iter = iter), 
          col = col.smooth, ...)
}

panel.hist <- function(x, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 1.5) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks; nB <- length(breaks)
  y <- h$counts; y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
}

pairs(cohort9_weight_wide[,c('Percent.WG','Percent.Fat.Pre_fasting','Percent.WL','Percent.FL','Percent.LL','Percent.LG','Percent.FG')],
          lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist)
```

````{r test_data_set, echo=FALSE}
start_fasting_interval <- 229
stop_fasting_interval <- 261

test_data <- merge(cohort9_weight_wide, annotated_clams_data[,c(1, 12:40)], by='Subject')
test_data$SumXYAmb <- test_data$X.Ambulatory+test_data$Y.Ambulatory

##Calculate the VO2. Before and during fasting, i.e. interval <158, use the Pre_fasting weight to calculate the VO2. After fasting, VO2 will be calculated using the After_fasting weight##
test_data$VO2.LBM <- ifelse(test_data$Interval<stop_fasting_interval,test_data$VO2/test_data$Lean.Pre_fasting, test_data$VO2/test_data$Lean.After_fasting)

test_data$Fast <- ifelse(test_data$Interval<start_fasting_interval,"Bf_fasting",ifelse(test_data$Interval>=stop_fasting_interval, "After_fasting", "During_fasting"))

variables <- c("Percent.WL", "Percent.WG", "Percent.LL", "Percent.LG", "Percent.FL", 
               "Percent.FG")

pairs(test_data[test_data$Light.Dark=="Light", c(15, 33, 49, 50)],
          lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist,
          main="LIGHT")

pairs(test_data[test_data$Light.Dark=="Dark",c(15, 33, 49, 50)],
          lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist,
        main="DARK")

cols <- c("Subject", "RER", "SumXYAmb", "VO2.LBM", "Fast", "Light.Dark")
cohort9_clams_LBM <- test_data[, cols]
cohort9_clams_LBM$Fast <- ifelse(cohort9_clams_LBM$Fast=="Bf_fasting",  "Pre_fasting", 
                                 ifelse(cohort9_clams_LBM$Fast=="After_fasting", "After_fasting", "During_fasting"))
cohort9_clams_LBM$Fast <- as.factor(cohort9_clams_LBM$Fast)

cohort9_mod <- merge(cohort9_weight, cohort9_clams_LBM, by.x=c("Subject", "Fasting_stat"), by.y=c("Subject", "Fast"), all=T)

cohort9_mod$Fasting_stat <- relevel(as.factor(cohort9_mod$Fasting_stat), ref='Pre_fasting')

cohort9_m_data<-
  cohort9_mod %>%
  group_by(Subject, Light.Dark, Fasting_stat) %>%
  summarise(
    RER = mean(RER),
    SumXYAmb = mean(SumXYAmb),
    VO2.LBM = mean(VO2.LBM),
    Lean=mean(Lean),
    Fat=mean(Fat),
    Percent.Fat=mean(Percent.Fat),
    Weight=mean(Weight))
cohort9_m_data<-as.data.frame(cohort9_m_data)

cohort9_m_data <- cohort9_m_data[!cohort9_m_data$Fasting_stat=="During_fasting",]
cohort9_m_data[is.na(cohort9_m_data$Light.Dark), 2] <- "Light"

write.csv(cohort9_m_data, file='../data/processed/cohort9_longitudinal_data_for_modelling.csv')


####prepare data for random forest
cols <- c('Subject','Light.Dark', 'Fast', 'Percent.LL', 'VO2.LBM', 'RER',  'SumXYAmb', 'Percent.WG', , 'Percent.WL', "Percent.FL",'Interval')

test_data$Fast <- as.factor(test_data$Fast)
cohort9_model_dat1<-test_data[,cols]

#summarized data in the pre-fasted subset by light/dark and animal.  Ignored the fasting data
cohort9_m_data<-
  subset(cohort9_model_dat1, Interval<start_fasting_interval) %>%
  group_by(Subject, Light.Dark) %>%
  summarise(
    Avg.Percent.LL = mean(Percent.LL),
    Avg.Percent.FL = mean(Percent.FL),
    RER = mean(RER),
    SumXYAmb = mean(SumXYAmb),
    VO2.LBM = mean(VO2.LBM),
    Percent.WG=mean(Percent.WG))
cohort9_model_data<-as.data.frame(cohort9_m_data)

write.csv(cohort9_model_data, file="../data/processed/cohort9_testing_data_for_modelling.csv")

cohort9_model_data_dark <- cohort9_model_data[cohort9_model_data$Light.Dark=="Dark",]
cohort9_model_data_light <- cohort9_model_data[cohort9_model_data$Light.Dark=="Light",]

pairs(cohort9_model_data_dark[,c('Percent.WG','RER','SumXYAmb','VO2.LBM')],
          lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist,
          main="LIGHT")

pairs(cohort9_model_data_light[,c('Percent.WG','RER','SumXYAmb','VO2.LBM')],
          lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist,
        main="DARK")
```

