#!/bin/bash

#PBS -N htseq
# Make the standard output and error streams are to be merged, intermixed, as
# standard output.
#PBS -j oe

#Request 6 hours of wall time
#PBS -l     cput=999:00:00
#PBS -l walltime=999:00:00

#Request 11 processors on 1 node
#PBS -l procs=11
#PBS -l pmem=40gb
#PBS -l nodes=compute-0-4
#PBS -r n

#get an email notice when job is done
#PBS -m e
#PBS -M dbridge9@uthsc.edu

PBS_O_WORKDIR="/home/dbridge/data/juvenile"
cd $PBS_O_WORKDIR

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

echo " "
echo " "
echo "Job started on `hostname` at `date`"

IN_FOLDER="tophat_output"
OUT_FOLDER="htseq-output"
GTF="reference-sequences/gencode.vM5.annotation.gtf"

rm $OUT_FOLDER
mkdir $OUT_FOLDER

for FILE in `ls $IN_FOLDER`
do 
  htseq-count --format=bam --stranded=yes --mode=intersection-nonempty $IN_FOLDER/$FILE/merged.bam $GTF > $OUT_FOLDER/$FILE-counts.txt
done

echo "Job ended at `date`"
echo " "

exit
